services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always
    env_file:
      - .env
    depends_on: [redis]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always
    depends_on: [backend]
    command: npm start

  redis:
    image: redis/redis-stack:latest
    command: ["redis-stack-server"]
    ports:
      - "6379:6379"