services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5050:5000"
    volumes:
      - ./backend:/app
    restart: always
    env_file:
      - .env
    depends_on: [redis-stack]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    restart: always
    depends_on: [backend]
    command: npm start

  redis-stack:
    image: redis/redis-stack
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"